<a href="https://colab.research.google.com/github/Leonaxi/Machine-Learning-in-Finance/blob/main/%E2%80%9CL9_LSMC_with_3_periods_ipynb%E2%80%9D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

discount = np.exp(-0.06)

# Regression at time 2
y = discount * np.array([0, 0.07, 0.18, 0.20, 0.09]) # payoff on t=3
x = np.array([1.08, 1.07, .97, .77, .84]) # stock price on t=2  
X = np.column_stack([np.ones_like(x), x, x**2])
Θ2 = np.linalg.lstsq(X, y)[0]
print(Θ2)

[-1.06998766  2.98341063 -1.81357618]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  if __name__ == '__main__':


In [2]:
np.linalg.lstsq(X, y)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


(array([-1.06998766,  2.98341063, -1.81357618]),
 array([0.01091272]),
 3,
 array([3.71663925, 0.3784075 , 0.00894256]))

In [4]:
# Value of not exercising
def P2(S2):
  X = np.column_stack([np.ones_like(x), x, x**2])
  return X @ Θ2

S2 = np.array([1.08, 1.07, .97, .77, .84]) 
P2(S2)

array([0.03674056, 0.04589834, 0.11752682, 0.15196921, 0.15641792])

In [5]:
# Value of exercising > value of not exercising, then exercise
val_if_dont_exercise = P2(S2)
val_if_exercise = np.maximum(1.1 - S2, 0)
val_if_exercise > val_if_dont_exercise

array([False, False,  True,  True,  True])

In [6]:
# For t = 1
r = 0.06
S1 = np.array([1.09, 0.93, .76, .92, .88])
X = np.column_stack([np.ones_like(S1), S1, S1**2])

y = np.array([0., 0.13, .33, .26, 0.]) * np.exp(-r)
Θ1 = np.linalg.lstsq(X, y)[0]

print(Θ1)

[ 2.03751234 -3.3354434   1.35645659]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  import sys


In [8]:
def P1(S1):
   X = np.column_stack([np.ones_like(S1), S1, S1**2])
   return X @  Θ1
  # 或者用法二：return Θ1[0] + Θ1[1] * S1+ Θ1[2] * S1**2

print(P1(S1))

[0.01348511 0.10874928 0.28606468 0.11700927 0.15276213]


In [9]:
# compare which value (exercise/not exercise) of put option price at t1 is higher
val_if_dont_exercise = P1(S1)
val_if_exercise = np.maximum(1.1 - S1, 0)
val_if_exercise > val_if_dont_exercise

array([False,  True,  True,  True,  True])

In [10]:
d = np.exp(-r)
DFC = np.array([0, 0, 0.07 * d, .17 * d**3, 0., .34 * d, 0.18 * d, 0.22 * d])
DFC

array([0.        , 0.        , 0.06592352, 0.14199594, 0.        ,
       0.32019994, 0.16951762, 0.2071882 ])

In [11]:
P0 = np.mean(DFC)
print(P0)


0.11310315101789473
